In [ ]:
#Installing dependencies
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps trl peft accelerate bitsandbytes xformers datasets

Collecting unsloth@ git+https://github.com/unslothai/unsloth.git (from unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-install-otfscm6t/unsloth_0ea1a3f16f8e4f868dda9a65c16164a6
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-install-otfscm6t/unsloth_0ea1a3f16f8e4f868dda9a65c16164a6
  Resolved https://github.com/unslothai/unsloth.git to commit 3ab282fd402cf6af03660c4d8d89a7d4ba9da1ff
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.24.1)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.12.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.6.0)
Collecting unsloth_zoo>=2026.3.2 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading unsloth_zoo-2026.3.2-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (26.0)
Collecting tyro (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading tyro-1.0.8-py3-none-any.whl.metadata (12 kB)
Collecting transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.2.0,>=4.51.3 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading transformers-5.2.0-py3-none-any.whl.metadata (32 kB)
Collecting datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.2.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (5.9.5)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.46.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.0.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (5.29.6)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.6.0)
Collecting hf_transfer (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (5.2.3)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.10.0+cu128)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.25.1)
Collecting pyarrow>=21.0.0 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.3.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.15.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.2.0,>=4.51.3->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.2.0,>=4.51.3->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.2.0,>=4.51.3->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.2.0,>=4.51.3->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.7.0)
Collecting torchao>=0.13.0 (from unsloth_zoo>=2026.3.2->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading torchao-0.16.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (20 kB)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.2->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.2->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.13.0)
Collecting trl!=0.19.0,<=0.24.0,>=0.18.2 (from unsloth_zoo>=2026.3.2->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.2->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.18.1)
Collecting cut_cross_entropy (from unsloth_zoo>=2026.3.2->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading cut_cross_entropy-25.1.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.2->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (11.3.0)
Collecting msgspec (from unsloth_zoo>=2026.3.2->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git)
  Downloading msgspec-0.20.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.4.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.16.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.0.4)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.17.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.5.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (2.19.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new]@ git+https://github.com/unslothai/unsloth.git) (9.10.2.21)

In [ ]:
#Importing necessary libraries

from unsloth import FastLanguageModel
from datasets import load_dataset, Dataset
from trl import SFTTrainer
from transformers import TrainingArguments
import torch
import json
import pandas as pd

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!

In [ ]:
#Loading Base model

max_seq_length = 2048

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Meta-Llama-3.1-8B-bnb-4bit",
    max_seq_length=max_seq_length,
    load_in_4bit=True,
)

==((====))==  Unsloth 2026.3.4: Fast Llama patching. Transformers: 5.2.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Will load unsloth/meta-llama-3.1-8b-bnb-4bit as a legacy tokenizer.

In [ ]:
#Adding LoRA adapters
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_alpha=16,
    lora_dropout=0
)

Not an error, but Unsloth cannot patch MLP layers with our manual autograd engine since either LoRA adapters
are not enabled or a bias term (like in Qwen) is used.
Unsloth 2026.3.4 patched 32 layers with 32 QKV layers, 32 O layers and 0 MLP layers.

In [ ]:
#Creating a dataset with 30 examples related software development resume bullet points

train_examples = [
    {
        "instruction": "Rewrite this resume bullet to be stronger for a software engineering role.",
        "input": "Built APIs for student platform.",
        "output": "Developed scalable backend APIs for a student platform, improving service reliability and supporting high-volume user workflows."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a software engineering role.",
        "input": "Worked on frontend for learning app.",
        "output": "Built responsive frontend features for a learning platform, improving usability and streamlining learner-facing workflows."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a software engineering role.",
        "input": "Used React to make UI components.",
        "output": "Developed reusable React components to improve UI consistency, maintainability, and development velocity across the application."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for an AI engineering role.",
        "input": "Made a chatbot using LLMs.",
        "output": "Built an LLM-powered chatbot that delivered context-aware responses, improving answer relevance and user interaction quality."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for an AI engineering role.",
        "input": "Used vector database for retrieval.",
        "output": "Integrated vector-based retrieval to support semantic search and improve grounding for LLM-generated responses."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a backend engineering role.",
        "input": "Worked with databases and queries.",
        "output": "Optimized database queries and data access patterns to improve backend performance and support scalable application workflows."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a cloud engineering role.",
        "input": "Deployed app on AWS.",
        "output": "Deployed and maintained cloud-native application services on AWS, improving scalability, availability, and operational efficiency."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a DevOps role.",
        "input": "Set up CI/CD pipelines.",
        "output": "Implemented CI/CD pipelines to automate build, test, and deployment workflows, reducing manual effort and improving release consistency."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a data engineering role.",
        "input": "Processed user activity data.",
        "output": "Built data processing workflows for user activity events, enabling structured analytics and faster insight generation."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a software engineering role.",
        "input": "Helped improve app performance.",
        "output": "Improved application performance through targeted optimizations, reducing latency and enhancing the overall user experience."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a backend engineering role.",
        "input": "Built microservices for platform.",
        "output": "Engineered backend microservices to support modular platform functionality, improving scalability and service maintainability."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a software engineering role.",
        "input": "Worked with authentication.",
        "output": "Implemented secure authentication and authorization workflows to protect user access and improve application security."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for an AI engineering role.",
        "input": "Fine tuned an LLM.",
        "output": "Fine-tuned an open-source LLM using parameter-efficient training methods to improve domain-specific response quality."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for an AI engineering role.",
        "input": "Evaluated model outputs.",
        "output": "Designed evaluation workflows to assess model output quality, identify failure patterns, and guide iterative model improvement."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a software engineering role.",
        "input": "Built dashboards for analytics.",
        "output": "Developed analytics dashboards to surface key product metrics and support data-informed decision making."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a mobile engineering role.",
        "input": "Worked on Android features.",
        "output": "Implemented Android application features that improved functionality, usability, and consistency across mobile workflows."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a frontend engineering role.",
        "input": "Improved website loading time.",
        "output": "Optimized frontend rendering and asset delivery to reduce page load times and improve user experience."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a software engineering role.",
        "input": "Used Docker for deployment.",
        "output": "Containerized application services with Docker to standardize environments and simplify deployment workflows."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a cloud engineering role.",
        "input": "Worked with serverless functions.",
        "output": "Developed serverless workflows to support event-driven processing and improve backend scalability."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a backend engineering role.",
        "input": "Created REST APIs using Node.js.",
        "output": "Built RESTful backend services in Node.js to support scalable application workflows and reliable client-server communication."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for an AI engineering role.",
        "input": "Built a RAG assistant.",
        "output": "Developed a retrieval-augmented generation assistant that combined semantic retrieval with LLM reasoning to produce context-grounded responses."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for an AI engineering role.",
        "input": "Used LangChain in a project.",
        "output": "Built LLM orchestration workflows with LangChain to manage retrieval, prompting, and response generation across AI application features."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a software engineering role.",
        "input": "Helped with debugging and bug fixing.",
        "output": "Diagnosed and resolved application issues to improve system stability, code quality, and release reliability."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a backend engineering role.",
        "input": "Worked on API integrations.",
        "output": "Integrated third-party APIs and backend services to extend application functionality and improve interoperability."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a data engineering role.",
        "input": "Built ETL pipelines.",
        "output": "Designed ETL pipelines to transform raw data into structured datasets for analytics and downstream processing."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a software engineering role.",
        "input": "Collaborated with team on features.",
        "output": "Collaborated across engineering teams to deliver production features aligned with product requirements and technical standards."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a frontend engineering role.",
        "input": "Used TypeScript in frontend work.",
        "output": "Built strongly typed frontend features with TypeScript to improve code maintainability and reduce runtime issues."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a DevOps role.",
        "input": "Monitored services in production.",
        "output": "Implemented production monitoring and alerting workflows to improve incident visibility and support faster issue resolution."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for an AI engineering role.",
        "input": "Worked with embeddings.",
        "output": "Used embedding-based representations to enable semantic retrieval and improve downstream LLM application performance."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a software engineering role.",
        "input": "Improved code quality.",
        "output": "Improved code quality through refactoring, testing, and development best practices, increasing maintainability and reducing defects."
    }
]

In [ ]:
#Defining Evaluation examples

eval_examples = [
    {
        "instruction": "Rewrite this resume bullet to be stronger for a software engineering role.",
        "input": "Built backend for app.",
        "output": "Developed backend services for an application, improving scalability, reliability, and support for core user workflows."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for an AI engineering role.",
        "input": "Made LLM app for documents.",
        "output": "Built an LLM application for document understanding, enabling context-aware responses from retrieved content."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a cloud engineering role.",
        "input": "Used AWS to host services.",
        "output": "Deployed and managed cloud services on AWS to support scalable, reliable application infrastructure."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a frontend engineering role.",
        "input": "Worked on React pages.",
        "output": "Developed React-based user interfaces that improved consistency, responsiveness, and overall user experience."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a backend engineering role.",
        "input": "Connected app with external APIs.",
        "output": "Integrated external APIs into backend workflows to expand functionality and support reliable data exchange."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a data engineering role.",
        "input": "Built pipelines for analytics.",
        "output": "Developed data pipelines to support structured analytics, reliable data flow, and faster reporting."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for an AI engineering role.",
        "input": "Worked on prompt engineering.",
        "output": "Designed prompt workflows to improve response relevance, consistency, and task performance in LLM-based applications."
    },
    {
        "instruction": "Rewrite this resume bullet to be stronger for a DevOps role.",
        "input": "Automated deployments.",
        "output": "Automated deployment workflows to improve release speed, consistency, and operational reliability."
    }
]

In [ ]:
#Saving these created datasets as JSONL files

with open("train.jsonl", "w", encoding="utf-8") as f:
    for ex in train_examples:
        f.write(json.dumps(ex) + "\n")

with open("eval.jsonl", "w", encoding="utf-8") as f:
    for ex in eval_examples:
        f.write(json.dumps(ex) + "\n")

print("Saved train.jsonl and eval.jsonl")

Saved train.jsonl and eval.jsonl

In [ ]:
#Loading these datasets

dataset=load_dataset("json", data_files={"train": "train.jsonl", "eval": "eval.jsonl"})
dataset

DatasetDict({
    train: Dataset({
        features: ['instruction', 'input', 'output'],
        num_rows: 30
    })
    eval: Dataset({
        features: ['instruction', 'input', 'output'],
        num_rows: 8
    })
})

In [ ]:
#Formatting the dataset for training the LLM

EOS_TOKEN = tokenizer.eos_token

def format_resume(example):
    text = (
        f"### Instruction:\n{example['instruction']}\n\n"
        f"### Input:\n{example['input']}\n\n"
        f"### Response:\n{example['output']}{EOS_TOKEN}"
    )
    return {"text": text}

dataset["train"] = dataset["train"].map(format_resume)
dataset["eval"] = dataset["eval"].map(format_resume)

In [ ]:
#Example from the formatted dataset

print(dataset["train"][0]["text"])

### Instruction:
Rewrite this resume bullet to be stronger for a software engineering role.

### Input:
Built APIs for student platform.

### Response:
Developed scalable backend APIs for a student platform, improving service reliability and supporting high-volume user workflows.<|end_of_text|>

In [ ]:
#Trainer

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["eval"],
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=5,
        max_steps=120,
        learning_rate=2e-4,
        logging_steps=5,
        eval_steps=10,
        #evaluation_strategy="steps",
        save_strategy="no",
        report_to="none",
        output_dir="outputs",
        seed=42,
    ),
)

In [ ]:
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 30 | Num Epochs = 30 | Total steps = 120
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 13,631,488 of 8,043,892,736 (0.17% trained)

TrainOutput(global_step=120, training_loss=0.58891698072354, metrics={'train_runtime': 271.0762, 'train_samples_per_second': 3.541, 'train_steps_per_second': 0.443, 'total_flos': 2076294394920960.0, 'train_loss': 0.58891698072354, 'epoch': 30.0})

In [ ]:
#Saving the fine tuned model

model.save_pretrained("resume_lora_adapter")
tokenizer.save_pretrained("resume_lora_adapter")

('resume_lora_adapter/tokenizer_config.json',
 'resume_lora_adapter/tokenizer.json')

In [ ]:
#Changing to inference mode

FastLanguageModel.for_inference(model)

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): LlamaForCausalLM(
      (model): LlamaModel(
        (embed_tokens): Embedding(128256, 4096, padding_idx=128004)
        (layers): ModuleList(
          (0-31): 32 x LlamaDecoderLayer(
            (self_attn): LlamaAttention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): LlamaMLP(
              (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
              (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
              (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
              (act_fn): SiLUActivation()
            )
            (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
            (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
          )
        )
        (norm): LlamaRMSNorm((4096,), eps=1e-05)
        (rotary_emb): LlamaRotaryEmbedding()
      )
      (lm_head): Linear(in_features=4096, out_features=128256, bias=False)
    )
  )
)

In [ ]:
#Testing simple examples

prompt = """### Instruction:
Rewrite this resume bullet to be stronger for an AI engineering role.

### Input:
Built chatbot for answering questions.

### Response:
"""

device = next(model.parameters()).device
inputs = tokenizer(prompt, return_tensors="pt").to(device)

outputs = model.generate(
    **inputs,
    max_new_tokens=80,
    do_sample=False,
    eos_token_id=tokenizer.eos_token_id,
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

### Instruction:
Rewrite this resume bullet to be stronger for an AI engineering role.

### Input:
Built chatbot for answering questions.

### Response:
Developed an LLM-powered chatbot that delivered context-aware responses, improving answer relevance and user interaction quality.

In [ ]:
#Helper Functions for Evaluation

def make_prompt(example):
    return (
        f"### Instruction:\n{example['instruction']}\n\n"
        f"### Input:\n{example['input']}\n\n"
        f"### Response:\n"
    )

def generate_answer(model, tokenizer, prompt, max_new_tokens=80):
    device = next(model.parameters()).device
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        eos_token_id=tokenizer.eos_token_id,
    )
    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return decoded[len(prompt):].strip() if decoded.startswith(prompt) else decoded.strip()

In [ ]:
#Evaluation on held out set

results = []

for ex in eval_examples:
    prompt = make_prompt(ex)
    prediction = generate_answer(model, tokenizer, prompt)

    results.append({
        "input": ex["input"],
        "expected": ex["output"],
        "prediction": prediction,
    })

df = pd.DataFrame(results)
df

,input,expected,prediction
0,Built backend for app.,"Developed backend services for an application,...",Developed scalable backend services to support...
1,Made LLM app for documents.,Built an LLM application for document understa...,Built an LLM application for semantic processi...
2,Used AWS to host services.,Deployed and managed cloud services on AWS to ...,Deployed serverless workflows on AWS to suppor...
3,Worked on React pages.,Developed React-based user interfaces that imp...,Built responsive React frontend features that ...
4,Connected app with external APIs.,Integrated external APIs into backend workflow...,Integrated third-party APIs and backend servic...
5,Built pipelines for analytics.,Developed data pipelines to support structured...,Engineered analytics pipelines to support scal...
6,Worked on prompt engineering.,Designed prompt workflows to improve response ...,Used prompt engineering to guide LLM input and...
7,Automated deployments.,Automated deployment workflows to improve rele...,Set up automated deployment workflows to reduc...

In [ ]:
#Evaluation Outputs

for row in results:
    print("INPUT:")
    print(row["input"])
    print("\nEXPECTED:")
    print(row["expected"])
    print("\nPREDICTION:")
    print(row["prediction"])
    print("\n" + "="*100 + "\n")

INPUT:
Built backend for app.

EXPECTED:
Developed backend services for an application, improving scalability, reliability, and support for core user workflows.

PREDICTION:
Developed scalable backend services to support application functionality, improving performance and reducing backend maintenance effort.

====================================================================================================

INPUT:
Made LLM app for documents.

EXPECTED:
Built an LLM application for document understanding, enabling context-aware responses from retrieved content.

PREDICTION:
Built an LLM application for semantic processing and document generation, improving answer quality and output coherence.

====================================================================================================

INPUT:
Used AWS to host services.

EXPECTED:
Deployed and managed cloud services on AWS to support scalable, reliable application infrastructure.

PREDICTION:
Deployed serverless workflows on AWS to support event-driven processing and improve backend scalability.

====================================================================================================

INPUT:
Worked on React pages.

EXPECTED:
Developed React-based user interfaces that improved consistency, responsiveness, and overall user experience.

PREDICTION:
Built responsive React frontend features that improved usability and consistency across application pages.

====================================================================================================

INPUT:
Connected app with external APIs.

EXPECTED:
Integrated external APIs into backend workflows to expand functionality and support reliable data exchange.

PREDICTION:
Integrated third-party APIs and backend services to extend application functionality and improve interoperability.

====================================================================================================

INPUT:
Built pipelines for analytics.

EXPECTED:
Developed data pipelines to support structured analytics, reliable data flow, and faster reporting.

PREDICTION:
Engineered analytics pipelines to support scalable data processing and faster insight generation.

====================================================================================================

INPUT:
Worked on prompt engineering.

EXPECTED:
Designed prompt workflows to improve response relevance, consistency, and task performance in LLM-based applications.

PREDICTION:
Used prompt engineering to guide LLM input and improve output quality for downstream AI applications.

====================================================================================================

INPUT:
Automated deployments.

EXPECTED:
Automated deployment workflows to improve release speed, consistency, and operational reliability.

PREDICTION:
Set up automated deployment workflows to reduce release friction and improve deployment consistency.

====================================================================================================

In [ ]:
#Manual Scoring Columns

scored_results = []

for row in results:
    scored_results.append({
        "input": row["input"],
        "expected": row["expected"],
        "prediction": row["prediction"],
        "strength_score": None,
        "clarity_score": None,
        "conciseness_score": None,
        "realism_score": None,
        "notes": ""
    })

score_df = pd.DataFrame(scored_results)
score_df

,input,expected,prediction,strength_score,clarity_score,conciseness_score,realism_score,notes
0,Built backend for app.,"Developed backend services for an application,...",Developed scalable backend services to support...,None,None,None,None,
1,Made LLM app for documents.,Built an LLM application for document understa...,Built an LLM application for semantic processi...,None,None,None,None,
2,Used AWS to host services.,Deployed and managed cloud services on AWS to ...,Deployed serverless workflows on AWS to suppor...,None,None,None,None,
3,Worked on React pages.,Developed React-based user interfaces that imp...,Built responsive React frontend features that ...,None,None,None,None,
4,Connected app with external APIs.,Integrated external APIs into backend workflow...,Integrated third-party APIs and backend servic...,None,None,None,None,
5,Built pipelines for analytics.,Developed data pipelines to support structured...,Engineered analytics pipelines to support scal...,None,None,None,None,
6,Worked on prompt engineering.,Designed prompt workflows to improve response ...,Used prompt engineering to guide LLM input and...,None,None,None,None,
7,Automated deployments.,Automated deployment workflows to improve rele...,Set up automated deployment workflows to reduc...,None,None,None,None,

In [ ]:
#Saving scored results csv

score_df.to_csv("evaluation_results_scored.csv", index=False)
print("Saved evaluation_results_scored.csv")

Saved evaluation_results_scored.csv

In [ ]:
#Downloading scored csv

from google.colab import files
files.download("evaluation_results_scored.csv")

In [ ]:
#Computing averages after manual scoring
scored = pd.read_csv("evaluation_results_scored_filled.csv")
scored
scored[["strength_score", "clarity_score", "conciseness_score", "realism_score"]].mean()

strength_score       3.625
clarity_score        4.500
conciseness_score    4.000
realism_score        3.750
dtype: float64

In [ ]:
#New base model

base_model, base_tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Meta-Llama-3.1-8B-bnb-4bit",
    max_seq_length=max_seq_length,
    load_in_4bit=True,
)

==((====))==  Unsloth 2026.3.4: Fast Llama patching. Transformers: 5.2.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Will load unsloth/meta-llama-3.1-8b-bnb-4bit as a legacy tokenizer.

In [ ]:
FastLanguageModel.for_inference(base_model)

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 4096, padding_idx=128004)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((4096,), eps=1e-05)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=4096, out_features=128256, bias=False)
)

In [ ]:
#Base model Evaluation on eval dataset

base_results = []

for ex in eval_examples:
    prompt = make_prompt(ex)
    prediction = generate_answer(base_model, base_tokenizer, prompt)

    base_results.append({
        "input": ex["input"],
        "expected": ex["output"],
        "base_prediction": prediction,
    })

base_df = pd.DataFrame(base_results)
base_df

,input,expected,base_prediction
0,Built backend for app.,"Developed backend services for an application,...","Built backend for app using Node.js, Express, ..."
1,Made LLM app for documents.,Built an LLM application for document understa...,Made LLM app for documents.
2,Used AWS to host services.,Deployed and managed cloud services on AWS to ...,"Used AWS to host services, including EC2, S3, ..."
3,Worked on React pages.,Developed React-based user interfaces that imp...,Worked on React pages to improve the user expe...
4,Connected app with external APIs.,Integrated external APIs into backend workflow...,"Connected app with external APIs, including a ..."
5,Built pipelines for analytics.,Developed data pipelines to support structured...,Built pipelines for data engineering.\n\n### I...
6,Worked on prompt engineering.,Designed prompt workflows to improve response ...,Worked on prompt engineering to improve the qu...
7,Automated deployments.,Automated deployment workflows to improve rele...,Automated deployments of applications and infr...

In [ ]:
#Fine tuned model on eval dataset

ft_results = []

for ex in eval_examples:
    prompt = make_prompt(ex)
    prediction = generate_answer(model, tokenizer, prompt)

    ft_results.append({
        "input": ex["input"],
        "expected": ex["output"],
        "finetuned_prediction": prediction,
    })

ft_df = pd.DataFrame(ft_results)
ft_df

,input,expected,finetuned_prediction
0,Built backend for app.,"Developed backend services for an application,...",Developed scalable backend services to support...
1,Made LLM app for documents.,Built an LLM application for document understa...,Built an LLM application for semantic processi...
2,Used AWS to host services.,Deployed and managed cloud services on AWS to ...,Deployed serverless workflows on AWS to suppor...
3,Worked on React pages.,Developed React-based user interfaces that imp...,Built responsive React frontend features that ...
4,Connected app with external APIs.,Integrated external APIs into backend workflow...,Integrated third-party APIs and backend servic...
5,Built pipelines for analytics.,Developed data pipelines to support structured...,Engineered analytics pipelines to support scal...
6,Worked on prompt engineering.,Designed prompt workflows to improve response ...,Used prompt engineering to guide LLM input and...
7,Automated deployments.,Automated deployment workflows to improve rele...,Set up automated deployment workflows to reduc...

In [ ]:
#Comparison Table

comparison_df = base_df.merge(ft_df, on=["input", "expected"])
comparison_df

,input,expected,base_prediction,finetuned_prediction
0,Built backend for app.,"Developed backend services for an application,...","Built backend for app using Node.js, Express, ...",Developed scalable backend services to support...
1,Made LLM app for documents.,Built an LLM application for document understa...,Made LLM app for documents.,Built an LLM application for semantic processi...
2,Used AWS to host services.,Deployed and managed cloud services on AWS to ...,"Used AWS to host services, including EC2, S3, ...",Deployed serverless workflows on AWS to suppor...
3,Worked on React pages.,Developed React-based user interfaces that imp...,Worked on React pages to improve the user expe...,Built responsive React frontend features that ...
4,Connected app with external APIs.,Integrated external APIs into backend workflow...,"Connected app with external APIs, including a ...",Integrated third-party APIs and backend servic...
5,Built pipelines for analytics.,Developed data pipelines to support structured...,Built pipelines for data engineering.\n\n### I...,Engineered analytics pipelines to support scal...
6,Worked on prompt engineering.,Designed prompt workflows to improve response ...,Worked on prompt engineering to improve the qu...,Used prompt engineering to guide LLM input and...
7,Automated deployments.,Automated deployment workflows to improve rele...,Automated deployments of applications and infr...,Set up automated deployment workflows to reduc...

In [ ]:
#Saving comparison results

comparison_df.to_csv("base_vs_finetuned_comparison.csv", index=False)
print("Saved base_vs_finetuned_comparison.csv")

Saved base_vs_finetuned_comparison.csv

In [ ]:
#Downloading the comparison csv

from google.colab import files
files.download("base_vs_finetuned_comparison.csv")

In [ ]:
#Importing manual rated comparison results csv

scored_comparision=pd.read_csv("base_vs_finetuned_comparison_rated.csv")
scored_comparision

,input,expected,base_prediction,finetuned_prediction,base_strength,base_clarity,base_conciseness,base_realism,ft_strength,ft_clarity,ft_conciseness,ft_realism,notes
0,Built backend for app.,"Developed backend services for an application,...","Built backend for app using Node.js, Express, ...",Developed scalable backend services to support...,3.0,2.0,1.0,2.0,4.0,5.0,4.0,4.0,Base adds unsupported tech stack details and e...
1,Made LLM app for documents.,Built an LLM application for document understa...,Made LLM app for documents.,Built an LLM application for semantic processi...,1.0,3.0,5.0,5.0,3.0,4.0,4.0,2.0,Base mostly repeats the original bullet. Fine-...
2,Used AWS to host services.,Deployed and managed cloud services on AWS to ...,"Used AWS to host services, including EC2, S3, ...",Deployed serverless workflows on AWS to suppor...,2.0,4.0,4.0,2.0,3.0,4.0,4.0,2.0,Both versions invent specifics. Base adds EC2/...
3,Worked on React pages.,Developed React-based user interfaces that imp...,Worked on React pages to improve the user expe...,Built responsive React frontend features that ...,2.0,2.0,1.0,4.0,4.0,5.0,4.0,4.0,Base has explanation leakage and only a small ...
4,Connected app with external APIs.,Integrated external APIs into backend workflow...,"Connected app with external APIs, including a ...",Integrated third-party APIs and backend servic...,3.0,2.0,1.0,2.0,4.0,5.0,4.0,5.0,Base injects specific API types plus explanati...
5,Built pipelines for analytics.,Developed data pipelines to support structured...,Built pipelines for data engineering.\n\n### I...,Engineered analytics pipelines to support scal...,1.0,1.0,1.0,2.0,4.0,4.0,4.0,4.0,Base output breaks badly with repetition and p...
6,Worked on prompt engineering.,Designed prompt workflows to improve response ...,Worked on prompt engineering to improve the qu...,Used prompt engineering to guide LLM input and...,2.0,2.0,1.0,4.0,3.0,4.0,4.0,4.0,Base includes explanation text; fine-tuned is ...
7,Automated deployments.,Automated deployment workflows to improve rele...,Automated deployments of applications and infr...,Set up automated deployment workflows to reduc...,3.0,2.0,1.0,5.0,4.0,5.0,4.0,5.0,Base is reasonable but hurt by explanation lea...

In [ ]:
#Computing comparison averages

base_cols = [
    "base_strength",
    "base_clarity",
    "base_conciseness",
    "base_realism"
]

ft_cols = [
    "ft_strength",
    "ft_clarity",
    "ft_conciseness",
    "ft_realism"
]

print("Base Model Averages")
print(scored_comparision[base_cols].mean())

print("\nFine-Tuned Model Averages")
print(scored_comparision[ft_cols].mean())

Base Model Averages
base_strength       2.125
base_clarity        2.250
base_conciseness    1.875
base_realism        3.250
dtype: float64

Fine-Tuned Model Averages
ft_strength       3.625
ft_clarity        4.500
ft_conciseness    4.000
ft_realism        3.750
dtype: float64

In [ ]:
#Improvement observed

delta = pd.Series({
    "strength": scored_comparision["ft_strength"].mean() - scored_comparision["base_strength"].mean(),
    "clarity": scored_comparision["ft_clarity"].mean() - scored_comparision["base_clarity"].mean(),
    "conciseness": scored_comparision["ft_conciseness"].mean() - scored_comparision["base_conciseness"].mean(),
    "realism": scored_comparision["ft_realism"].mean() - scored_comparision["base_realism"].mean(),
})

print("Improvement (Fine-tuned minus Base)")
print(delta)

Improvement (Fine-tuned minus Base)
strength       1.500
clarity        2.250
conciseness    2.125
realism        0.500
dtype: float64

In [ ]:
#Identifying failure Patterns

scored_comparision[[
    "input",
    "base_prediction",
    "finetuned_prediction"
]]

,input,base_prediction,finetuned_prediction
0,Built backend for app.,"Built backend for app using Node.js, Express, ...",Developed scalable backend services to support...
1,Made LLM app for documents.,Made LLM app for documents.,Built an LLM application for semantic processi...
2,Used AWS to host services.,"Used AWS to host services, including EC2, S3, ...",Deployed serverless workflows on AWS to suppor...
3,Worked on React pages.,Worked on React pages to improve the user expe...,Built responsive React frontend features that ...
4,Connected app with external APIs.,"Connected app with external APIs, including a ...",Integrated third-party APIs and backend servic...
5,Built pipelines for analytics.,Built pipelines for data engineering.\n\n### I...,Engineered analytics pipelines to support scal...
6,Worked on prompt engineering.,Worked on prompt engineering to improve the qu...,Used prompt engineering to guide LLM input and...
7,Automated deployments.,Automated deployments of applications and infr...,Set up automated deployment workflows to reduc...

In [ ]:
#The end of Common ML loop